### ISSUE TITLE
Confusion in FID score 

### ISSUE THREAD

**Issue by artikeshari** [wyhsirius/g3an-project#6]
Hello, Thanks for releasing the code. 
I train your code on the UvA NEMO dataset and found that after 1200 epoch the FID is 52.44, and at 2200 epoch, the FID is 58.12 as you mentioned. 
What number of epoch should we consider for evaluation? how did you decide? Because, loss is not giving any idea of convergence.

**Comment by wyhsirius** [comment]
@sampriti111 This is a good question. Since it is not practical to evaluate checkpoint after each epoch, you can choose to evaluate every 100 or 500 epochs.
