### ISSUE TITLE
Pre/post processing for Weizmann dataset

### ISSUE THREAD

**Issue by artikeshari** [wyhsirius/g3an-project#7]
Hi,

Can you share the detail about the pre/post-processing that you applied to put qualitative results for the Weizmann dataset, in the paper?  It seems you have cropped the frames to enlarge the person in the center.

**Comment by wyhsirius** [comment]
@sampriti111 Hi, I used the preprocessed data from MoCoGAN

**Comment by artikeshari** [comment]
Mocogan says they have used 96x96 reshaping for the Weizmann dataset and you are using 64x64. I used preprocessing as mentioned in your paper; scale each frame to 85 × 64 and crop the central 64 × 64 regions. But processed frames shape does not look like frames that you have added to the paper.  I just wanted to know if you have used some post-processing on frames to put in the paper.

**Comment by wyhsirius** [comment]
@sampriti111 I didn't use any post-processing. I used the data provided by mocogan on its github

**Comment by artikeshari** [comment]
I misunderstood preprocessing part of the paper. Thanks btw.

**Comment by artikeshari** [comment]
Hey, I have one more doubt. You have mentioned that "The Weizmann Action dataset consists of videos of 9 subjects, performing 10 actions such as wave and bend." But, the GitHub repo of [MoCoGAN](https://github.com/sergeytulyakov/mocogan) only has 4 categories- bending, jumping jack, one hand waving, and two hands waving performed by 9 subjects, which means 36 original +36 flipped videos. 

If you are downloading the data from somewhere else please let me know.

**Comment by wyhsirius** [comment]
@sampriti111 Hi, this is true. In our experiments, we only used the 4 categories as MoCoGAN to have a fair comparison.
