### ISSUE TITLE
Any plan to release conditional generation code?

### ISSUE THREAD

**Issue by zgzxy001** [wyhsirius/g3an-project#8]
Hi, thank you for your great work! Do you have any plan to release the conditional generation code? Thanks!

**Comment by wyhsirius** [comment]
@zgzxy001 Hi, thanks for your interest of our work. We plan to release the conditional generation. I am sorry for such long time delay. We currently have issue to access our original cluster. Once it is solved, I will update this folder ASAP.

**Comment by zgzxy001** [comment]
Thank you!
